package com.hibernate.table;
// Generated Nov 27, 2013 9:08:41 AM by Hibernate Tools 3.2.1.GA



/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private Integer no;
     private String nim;
     private String nama;

    public Mahasiswa() {
    }

    public Mahasiswa(String nim, String nama) {
       this.nim = nim;
       this.nama = nama;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


