package com.hibernate.table;
// Generated Nov 27, 2013 9:08:41 AM by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer no;
     private String idusers;
     private String password;

    public Users() {
    }

    public Users(String idusers, String password) {
       this.idusers = idusers;
       this.password = password;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public String getIdusers() {
        return this.idusers;
    }
    
    public void setIdusers(String idusers) {
        this.idusers = idusers;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


